// <auto-generated />
namespace Mimari_Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Asasad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Asasad));
        
        string IMigrationMetadata.Id
        {
            get { return "202202181038508_Asasad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
